Support New HF metadata Format
coreweave/gpt_bpe pull request #1
Opened 2023-02-16 16:49 UTC by Rexwang8

gpt_bpe Repo -- model downloader.

Pythia models from ElutherAI now follows the new HF metadata format for transformer models, where the merges.txt and vocab.json is folded into the tokenizer.json file under a key entry each. This PR will check for this new format and attempt to unfold the json data (ie generate a separate vocab.json, merges.txt) from the tokenizer.json file, allowing for direct HF support for pythia models and others of similar formats.

Work was done jointly by Rex and Rahul.

2023-02-16 18:35 UTC, rtalaricw commented on resources/resolver.go
> +			"safety_checker/pytorch_model.json":          RESOURCE_OPTIONAL,
Why did we change DIFFUSER code when we only were touching TRANSFORMERS? @Rexwang8

2023-02-23 14:08 UTC, wbrown requested changes
Confusing Boolean logic that needs to be corrected, otherwise LGTM.

2023-02-23 14:08 UTC, wbrown commented on resources/resolver.go
> +	if flagVocabExists {
These flags are inverse of the usual case.  The variable name implies that the Boolean is testing for existence, and `true` means it does exist.  But it's actually `false` where it does exist.

It should be `flagVocabNotExist` or make the function call `CheckFileExist`. Either way, it should be `!flagVocabExists` for this and the following.

2023-02-23 16:28 UTC, Rexwang8 commented
fixed, everything appears to be working locally

2023-02-23 16:29 UTC, merged