refactor: seperate file load and process
coreweave/gpt_bpe pull request #19
Opened 2024-07-16 15:41 UTC by Rexwang8

## Summary
This PR and following will aim to address gpt_bpe's confusing structure of file loading and initial processing during the process of creating an encoder. It aims to meet the code quality requirements to be merged back upstream to wbrown/gpt_bpe .

## Changes
GPT_BPE is able to create an encoder using files from embedded, local, or remote. Previously, embedded and local/remote had two separate but parallel code paths related to file loading and initial processing which caused duplication of code. In this PR, I have separated this code into a single step for loading resources and a single step for initial processing.

I have also removed the mistral specific config structs in favor of expanding the hfconfig struct.

I have also added a test case that downloads pythia-70m remotely (not embedded) and tests the functionality of the pythia provided tokenizer against a reference generated by python transformer library.

2024-07-16 15:53 UTC, wbrown requested changes
Quick scan, will review and test more later.

2024-07-16 15:53 UTC, wbrown commented on gpt_bpe.go
> +		hfConfig.AddEosToken = &eosBosBool
You really should not be assigning a pointer value to two different variables.

What you are doing here is pointing to the same variable. If someone changes the value, it's going to change for both values.

Create a new `bosBool` value, and rename the prior one to `eosBool`.

2024-07-16 15:53 UTC, wbrown commented on resources/resolver.go
> +// ResolveResourcesFromRemoteOrLocal
Why do we need such a long function name? Just call it `ResolveResources`.

We've spoken about these. :)

2024-07-16 15:53 UTC, wbrown commented on resources/resolver.go
> +		hasReadForVocabSize := false
`hasReadForEosBos`

2024-07-16 15:53 UTC, wbrown commented on resources/resolver.go
> +			if eosTokenId, ok := config.(map[string]interface{})["eos_token_id"].(float64); ok {
Rather than doing `config.(map[string]interface{})` repeatedly, assign that to a variable and use that variable.

2024-07-16 15:53 UTC, wbrown commented on resources/resolver.go
> -			BosTokenStr: &bosText,
Do we not have default values there anymore?

2024-07-16 15:53 UTC, wbrown commented on resources/resolver.go
> +	if err != nil {
As I've said, no point to this long-ass function name. :)

2024-07-16 22:12 UTC, rtalaricw requested changes
Few comments for design and modularity

2024-07-16 22:12 UTC, rtalaricw commented on resources/resolver.go
> +	}
The formatting for these nested if-else statements are very confusing to comprehend. Can you use go fmt to tidy up your code before committing please?

2024-07-16 22:12 UTC, rtalaricw commented on resources/resolver.go
> +						*hfConfig.PadTokenId = uint16(padTokenInt)
You should be able to remove the nested if statement with something like :

```
if hfConfig.PadTokenStr != nil {
    if padTokenInt, ok := vocabMap[*(hfConfig.PadTokenStr)].(float64); ok {
        hfConfig.PadTokenId = new(uint16)
        *hfConfig.PadTokenId = uint16(padTokenInt)
    }
}
```

2024-07-16 22:12 UTC, rtalaricw commented on resources/resolver.go
> +		if _, err := resources.GetFile("encoder.json"); err == nil {
Can you add comments as to what is going on here as well?

2024-07-16 22:12 UTC, rtalaricw commented on resources/resolver.go
> -			if !hasReadConfig {
I feel like this function can be broken down in the separate formats that you check for like Pythia, Llama and Mistral. Can we make the functionality modular so the logic is not convoluted. It is very hard to read this function without comments or an understanding of the three formats that you are checking for. We should have separate functions for each with comments on specific differences in formats so that when adding a new format it becomes much easier.

2024-07-18 15:22 UTC, Rexwang8 commented on resources/resolver.go
> -			if !hasReadConfig {
the current read method is broken down by file, and then by format, we can also break it down by format and then by file, but I'm unsure if this is any better really, as for separate functions and the like, the entire purpose of this PR is to reduce model-specific hard coding as much as possible, so model-specific functions seem counter-intuitive to me.

2024-07-18 15:23 UTC, Rexwang8 commented on resources/resolver.go
> +	}
This is after go fmt already

2024-07-18 17:27 UTC, rtalaricw commented on resources/resolver.go
> -			if !hasReadConfig {
Could we encapsulate it so there is Template1/Format1 (with EOS/BOS as strings), Template2/Format2 (with EOS/BOS as a nested dict) etc. instead of specifying Llama, Mistal etc.? 

I just think splitting up such a large function into smaller modular functions that have comments about what the difference in format is and why we are using that particular functionality to inject into the Read.. function would be really helpful in the future to add new Templates/Formats. 

This can go in a later PR as well if it is too much of a hassle but food for thought.

2024-07-19 16:00 UTC, Rexwang8 commented on resources/resolver.go
> -			if !hasReadConfig {
Would prob go into another PR if needed

2024-07-19 16:04 UTC, merged